/*! Copyright (c) 2018 Siemens AG. Licensed under the MIT License. */

import { CoatyObject, Uuid } from "./object";

/**
 * Represents a snapshot in time of the state of any Coaty object.
 * A snapshot is typically generated by an instance of the `HistorianController`
 * class. The property `parentObjectId` is inherited from the base CoatyObject type
 * and needs to be set in a Snapshot. This is automatically validated 
 * by the framework.
 */
export interface Snapshot extends CoatyObject {

    coreType: "Snapshot";

    /**
     * Timestamp when snapshot was issued/created.
     * Value represents the number of milliseconds since the epoc in UTC
     * (see Date.getTime(), Date.now()).
     */
    creationTimestamp: number;

    /**
     * UUID of controller which created this snapshot.
     */
    creatorId: Uuid;

    /**
     * Tags associated with this snapshot (optional). They can be used on
     * retrieval to identify different purposes of the snapshot.
     */
    tags?: string[];

    /**
     * Deep copy of the object and its state stored in this snapshot. 
     */
    object: CoatyObject;
}
