/*! -----------------------------------------------------------------------------
 * <auto-generated>
 *     This code was generated by a tool.
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 * </auto-generated>
 * ------------------------------------------------------------------------------
 * Copyright (c) 2019 Siemens AG. Licensed under the MIT License.
 */

import { AgentInfo } from "coaty/runtime";

export const agentInfo: AgentInfo = {
    packageInfo: {
        name: "sensor-things-dashboard",
        version: "1.2.4",
    },
    buildInfo: {
        buildDate: "2019-02-04T17:14:01+01:00",
        buildMode: "development",
    },
    configInfo: {
        serviceHost: "",
    },
};
