source "https://rubygems.org"

# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
#gem "jekyll", "~> 3.8.4"

# This is the theme for new Jekyll sites. You may change this to anything you like.
gem "jekyll-theme-primer", "~> 0.5.3"

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
gem "github-pages", group: :jekyll_plugins

# If you have any plugins, put them here!
group :jekyll_plugins do
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.0" if Gem.win_platform?

# Fix security alert on CVE-2018-14404
# Fix security alert on CVE-2019-5477
# Fix securitry alert on CVE-2020-7595
gem "nokogiri", ">= 1.10.8"

# Fix security alert on CVE-2019-16892
gem "rubyzip", ">= 1.3.0"

# Fix security alert on CVE-2020-8165
gem "activesupport", ">= 5.2.4.3"
